### PR TITLE
 Cross-compilation

### PR DESCRIPTION
**Pull request by stevehayles**
dart.lib is a required library on windows only but the previous build.rs made the linking conditional on the host OS type which caused problems compiling on a Windows host for another operating system. 

When using dart-sys on a windows host machine but compiling for a non-windows target the original logic would still try and link the dart library.  There is still potentially an edge case of compiling FOR a windows target on a non-windows host but that wasn't covered previously.

### CODE REVIEW

**Comment by OptimisticPeach** [comment]
I'm rather sorry to disappoint. Unfortunately, I don't really have time to maintain this anymore, but feel free to PR or fork (depending on what you want).

**Comment by OptimisticPeach** [comment]
Oh shoot, I totally misread the page, this _is_ a PR. I'll get to reviewing it :)

**Comment by gutenfries** [comment]
Please see https://github.com/fzyzcjy/flutter_rust_bridge/pull/894

Thank you!

**Comment by gutenfries** [comment]
If there is no activity here for 48 hours, I am going to mark this `stale` and close it.

thanks! :)

**Comment by gutenfries** [comment]
marking this as stale.

**Pull request closed without merging**
